// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGGzYILW7viK9RdxnsjjjhKwL3o95Qogg',
    appId: '1:952774447751:web:f043b10eb613886b9e1e22',
    messagingSenderId: '952774447751',
    projectId: 'noteai-1',
    authDomain: 'noteai-1.firebaseapp.com',
    storageBucket: 'noteai-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByHi7S0Rt3O9Y217mXpEO0dv-1Tfxt62s',
    appId: '1:952774447751:android:354a7642d619151a9e1e22',
    messagingSenderId: '952774447751',
    projectId: 'noteai-1',
    storageBucket: 'noteai-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_aLERfoBA3BNUrIc1MmhOqM-G99WUsTg',
    appId: '1:952774447751:ios:bc771398d91a91e39e1e22',
    messagingSenderId: '952774447751',
    projectId: 'noteai-1',
    storageBucket: 'noteai-1.appspot.com',
    iosBundleId: 'com.example.noteAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_aLERfoBA3BNUrIc1MmhOqM-G99WUsTg',
    appId: '1:952774447751:ios:bc771398d91a91e39e1e22',
    messagingSenderId: '952774447751',
    projectId: 'noteai-1',
    storageBucket: 'noteai-1.appspot.com',
    iosBundleId: 'com.example.noteAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGGzYILW7viK9RdxnsjjjhKwL3o95Qogg',
    appId: '1:952774447751:web:1bbc70d80531478a9e1e22',
    messagingSenderId: '952774447751',
    projectId: 'noteai-1',
    authDomain: 'noteai-1.firebaseapp.com',
    storageBucket: 'noteai-1.appspot.com',
  );

}